#!/bin/sh
set -e

# --------------------------------------
# Minimal init for Aember Init System
# --------------------------------------

echo "[init][info] Creating early mount points..."
mkdir -p /proc /sys /dev /tmp

echo "[init][info] Mounting early filesystems..."
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

echo "[init][info] Early mounts done. Handing over to Aember (PID 1)..."

# --------------------------------------
# Start Aember as PID 1
# Aember will handle pivot_root to real root,
# mount essential filesystems, and start services.
# --------------------------------------
exec /usr/bin/aember
