BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb"

BBFILE_COLLECTIONS += "aember"
BBFILE_PATTERN_aember := "^${LAYERDIR}/"
BBFILE_PRIORITY_aember = "6"

# THIS IS THE COMPATIBILITY LIST
LAYERSERIES_COMPAT_aember = "whinlatter"
