# Layer configuration for meta-myinit
BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb"

BBFILE_COLLECTIONS += "myinit"
BBFILE_PATTERN_myinit = "^${LAYERDIR}/"
BBFILE_PRIORITY_myinit = "6"