#!/bin/sh

echo "[init] Creating mount points..."
mkdir -p /proc /sys /dev

echo "[init] Mounting filesystems..."
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

#echo "[init] Starting serial console shell on ttyS0..."
#setsid /bin/ash --login < /dev/ttyS0 > /dev/ttyS0 2>&1 &

echo "[init] Launching Aember as PID 1..."
exec /usr/bin/aember
