# We are layer 'aember-image'
BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "aember"
BBFILE_PATTERN_aember = "^${LAYERDIR}/"
BBFILE_PRIORITY_aember = "6"


LAYERSERIES_COMPAT_aember = "whinlatter"