# Standard override for ARM32
MACHINEOVERRIDES =. "arm:"

require conf/machine/include/arm/armv7a/tune-cortexa9.inc

KERNEL_IMAGETYPE = "zImage"
SERIAL_CONSOLES = "115200;ttyAMA0"
PREFERRED_PROVIDER_virtual/kernel = "aember-kernel"

# ARM32 specific settings
DEFAULTTUNE = "cortexa9hf-neon"
