# Standard override for ARM 32-bit
MACHINEOVERRIDES =. "arm:"

require conf/machine/include/arm/armv7a/tune-cortexa9.inc

KERNEL_IMAGETYPE = "zImage"
SERIAL_CONSOLES = "115200;ttyAMA0"
PREFERRED_PROVIDER_virtual/kernel = "aember-kernel"

# ARM 32-bit specific settings
DEFAULTTUNE = "cortexa9hf-neon"