# Standard override for ARM64
MACHINEOVERRIDES =. "aarch64:"

require conf/machine/include/arm/armv8a/tune-cortexa72.inc

KERNEL_IMAGETYPE = "Image"
SERIAL_CONSOLES = "115200;ttyAMA0"
PREFERRED_PROVIDER_virtual/kernel = "aember-kernel"

# ARM64 specific settings
DEFAULTTUNE = "cortexa72"
