#!/bin/bash

AUTOCOMPLETE_SCRIPT="$(pwd)/python/autocomplete/autocomplete_aember.py"

echo -e "\n# Enable bash-completion" >> ~/.bashrc
echo -e "if [ -f /etc/bash_completion ]; then" >> ~/.bashrc
echo -e "   . /etc/bash_completion" >> ~/.bashrc
echo -e "fi" >> ~/.bashrc

STRING='$(python3 '
ENDING='"${words[@]:1}"'

# Add the autocomplete function .bashrc dynamically
echo -e "\n_autocomplete_aember() {" >> ~/.bashrc
echo -e "\tlocal cur prev words cword" >> ~/.bashrc
echo -e "\t_init_completion || return" >> ~/.bashrc
echo -ne "\n\tCOMPREPLY=($STRING " >> ~/.bashrc
echo -ne "$AUTOCOMPLETE_SCRIPT  " >> ~/.bashrc
echo -e  "$ENDING))\n" >> ~/.bashrc
echo -e "}" >> ~/.bashrc
echo -e "\ncomplete -F _autocomplete_aember aember" >> ~/.bashrc

echo -e "export CI=true" >> ~/.bashrc

USER_COLOR='\033[32m'
DOCKER_COLOR='\033[34m'
PATH_COLOR='\033[35m'
COMMAND_COLOR='\033[38;5;214m'
BOLD='\033[1m'
RESET_COLOR='\033[0m'

echo "PS1='${BOLD}\[${USER_COLOR}\]\u\[${RESET_COLOR}\]@${BOLD}\[${DOCKER_COLOR}\]aember\[${RESET_COLOR}\]:${BOLD}\[${PATH_COLOR}\]\w\[${RESET_COLOR}\]${COMMAND_COLOR}\$ ${RESET_COLOR}'" >> ~/.bashrc

ln -s "$(pwd)/python/run.py" /venv/bin/aember

source ~/.bashrc
source /venv/bin/activate


figlet -f big aember | lolcat

bash