BBLAYERS ?= " \
  /aember_mountfs/aember_ws/aember/poky/meta \
  /aember_mountfs/aember_ws/aember/poky/meta-poky \
  /aember_mountfs/aember_ws/aember/poky/meta-yocto-bsp \
  /aember_mountfs/aember_ws/aember/resources/poky/poky-recipes/x64-linux/aember-image \
"
