
MACHINE ?= "qemux86-64"
DISTRO ?= "poky"

INITRAMFS_IMAGE = "aember-initramfs"
INITRAMFS_IMAGE_NAME = "aember-initramfs-${MACHINE}.rootfs"

DL_DIR ?= "/home/arian/aember_ws/aember/resources/poky/poky-cache/universal/downloads"
SSTATE_DIR ?= "/home/arian/aember_ws/aember/resources/poky/poky-cache/x64-linux/sstate-cache"
TMPDIR = "/home/arian/aember_ws/aember/resources/poky/poky-cache/x64-linux/tmp"

# Only generate an initramfs cpio
IMAGE_FSTYPES = "cpio.gz"

# No extras
EXTRA_IMAGE_FEATURES = ""
IMAGE_FEATURES = ""

# Use smallest package format
PACKAGE_CLASSES = "package_ipk"

# Force busybox for runtime
VIRTUAL-RUNTIME_init_manager = "busybox"
VIRTUAL-RUNTIME_initscripts = ""
VIRTUAL-RUNTIME_login_manager = "busybox"
VIRTUAL-RUNTIME_dev_manager = "busybox-mdev"

# Bundle our custom initramfs
INITRAMFS_IMAGE = "aember-initramfs"
INITRAMFS_IMAGE_BUNDLE = "1"
